export const BG='#1a1a1a',BG2='#242424',BG3='#2e2e2e',ORG='#a3e635',ORG2='#bef264',GOLD='#a3e635',GRN='#a3e635',BDR='rgba(255,255,255,0.08)',TXT='#f0f0f0',MUT='#a0a0a0',DIM='#666666';
export const SANS="'Inter','Helvetica Neue',sans-serif",DISP="'Bebas Neue','Arial Black',sans-serif";
export const ADMIN_PW='LongShot2026',SEED_KEY='rb_seed_v12',ORGS_KEY='rb_orgs',ENT_KEY='rb_entries';
export const EJS_SERVICE='service_ijz7h1p',EJS_TEMPLATE_NOTIF='template_9w26xwm',EJS_TEMPLATE_CONTACT='template_21fdarp',EJS_KEY='jQT8w9IWlDWFVXTri';
export const BADGES={platinum:{label:'Platinum Verified',icon:'💎',color:'#bfdbfe',bg:'rgba(147,197,253,0.1)',border:'rgba(147,197,253,0.3)'},tour:{label:'Tour Verified',icon:'★',color:GOLD,bg:'rgba(240,180,41,0.1)',border:'rgba(240,180,41,0.35)'},amateur:{label:'Amateur Verified',icon:'✅',color:GRN,bg:'rgba(34,197,94,0.1)',border:'rgba(34,197,94,0.3)'}};
export const COUNTRIES=[{code:'AF',name:'Afghanistan'},{code:'AL',name:'Albania'},{code:'DZ',name:'Algeria'},{code:'AR',name:'Argentina'},{code:'AU',name:'Australia'},{code:'AT',name:'Austria'},{code:'BH',name:'Bahrain'},{code:'BE',name:'Belgium'},{code:'BR',name:'Brazil'},{code:'BG',name:'Bulgaria'},{code:'KH',name:'Cambodia'},{code:'CA',name:'Canada'},{code:'CL',name:'Chile'},{code:'CN',name:'China'},{code:'CO',name:'Colombia'},{code:'HR',name:'Croatia'},{code:'CZ',name:'Czech Republic'},{code:'DK',name:'Denmark'},{code:'EG',name:'Egypt'},{code:'FI',name:'Finland'},{code:'FR',name:'France'},{code:'DE',name:'Germany'},{code:'GH',name:'Ghana'},{code:'GR',name:'Greece'},{code:'HK',name:'Hong Kong'},{code:'HU',name:'Hungary'},{code:'IN',name:'India'},{code:'ID',name:'Indonesia'},{code:'IE',name:'Ireland'},{code:'IL',name:'Israel'},{code:'IT',name:'Italy'},{code:'JP',name:'Japan'},{code:'KE',name:'Kenya'},{code:'KR',name:'South Korea'},{code:'KW',name:'Kuwait'},{code:'MY',name:'Malaysia'},{code:'MX',name:'Mexico'},{code:'MA',name:'Morocco'},{code:'NL',name:'Netherlands'},{code:'NZ',name:'New Zealand'},{code:'NG',name:'Nigeria'},{code:'NO',name:'Norway'},{code:'OM',name:'Oman'},{code:'PK',name:'Pakistan'},{code:'PH',name:'Philippines'},{code:'PL',name:'Poland'},{code:'PT',name:'Portugal'},{code:'QA',name:'Qatar'},{code:'RO',name:'Romania'},{code:'RU',name:'Russia'},{code:'SA',name:'Saudi Arabia'},{code:'SG',name:'Singapore'},{code:'ZA',name:'South Africa'},{code:'ES',name:'Spain'},{code:'SE',name:'Sweden'},{code:'CH',name:'Switzerland'},{code:'TW',name:'Taiwan'},{code:'TH',name:'Thailand'},{code:'TR',name:'Turkey'},{code:'AE',name:'UAE'},{code:'GB',name:'United Kingdom'},{code:'US',name:'United States'},{code:'UY',name:'Uruguay'},{code:'VN',name:'Vietnam'},{code:'ZW',name:'Zimbabwe'}];
export const toSlug=str=>str.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export const todayStr=()=>new Date().toISOString().slice(0,10);
export const fmtDate=d=>{try{return new Date(d+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});}catch{return d;}};
export const tier=d=>d>=350?'🟡 Elite':d>=300?'🟢 Pro':d>=250?'🔵 Strong':'⚪ Amateur';
export const tierClr=()=>'#a3e635';
export const toB64=f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f);});
export function isoWeek(dateStr){const d=new Date(dateStr+'T12:00:00');const j4=new Date(d.getFullYear(),0,4);const mon=new Date(j4);mon.setDate(j4.getDate()-((j4.getDay()+6)%7));const w=Math.floor((d-mon)/(7*864e5))+1;return{y:d.getFullYear(),w};}
export function nowWeek(){return isoWeek(new Date().toISOString().slice(0,10));}
export function weekLabel({y,w}){const j4=new Date(y,0,4),mon=new Date(j4);mon.setDate(j4.getDate()-((j4.getDay()+6)%7)+(w-1)*7);const sun=new Date(mon);sun.setDate(mon.getDate()+6);const f=d=>d.toLocaleDateString('en-GB',{day:'numeric',month:'short'});return `Wk ${w} ${f(mon)} – ${f(sun)} ${y}`;}
export function sameWeek(ds,{y,w}){const x=isoWeek(ds);return x.y===y&&x.w===w;}
export function prevWeek({y,w}){return w===1?{y:y-1,w:52}:{y,w:w-1};}
export function nextWeek({y,w}){const nw=nowWeek();if(y>nw.y||(y===nw.y&&w>=nw.w))return{y,w};return w===52?{y:y+1,w:1}:{y,w:w+1};}
